version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
    - docker.env
    ports: 
    - 8030:8030
    volumes:
    - ./:/usr/app
    image: jott-api
    depends_on:
    - db
    command: npm run dev

  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redisdata:/data
  db:
    image: mysql
    restart: always
    env_file:
    - docker.env
    # environment:
    # - MYSQL_USER=$MYSQL_USER
    # - MYSQL_PASSWORD=$MYSQL_PASSWORD
    # - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    # - MYSQL_DATABASE=$MYSQL_DATABASE
    # MYSQL_DATABASE:
    # MYSQL_USER:
    # MYSQL_PASSWORD:
    # MYSQL_ROOT_PASSWORD:
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - data-db:/var/lib/mysql


volumes:
  redisdata:
  data-db: